{
 "title": "Alerts: Now",
 "tags": [
  "alerts",
  "analytics",
  "now"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "alertname",
    "label": "Alert name",
    "query": "label_values(ALERTS{alertstate=\"firing\"}, alertname)"
   },
   {
    "name": "name",
    "label": "Name",
    "query": "label_values(ALERTS{alertstate=\"firing\"}, name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Operational: Active by severity (now)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (severity) (\n  ALERTS{alertstate=\"firing\", alertname=~\"$alertname\", name=~\"$name\"}\n  unless on(alertname, name)\n  ALERTS{alertstate=\"firing\", notify=\"off\", alertname=~\"$alertname\", name=~\"$name\"}\n)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Operational: Active alerts (now)",
   "type": "table",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "(\n  ALERTS{alertstate=\"firing\", alertname=~\"$alertname\", name=~\"$name\"}\n  unless on(alertname, name)\n  ALERTS{alertstate=\"firing\", notify=\"off\", alertname=~\"$alertname\", name=~\"$name\"}\n)"
    }
   ]
  },
  {
   "title": "Statistical: Active by alertname (now)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (alertname) (ALERTS{alertstate=\"firing\", notify=\"off\", alertname=~\"$alertname\", name=~\"$name\"})",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Statistical: Active alerts (now)",
   "type": "table",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 8 },
   "targets": [
    {
     "expr": "ALERTS{alertstate=\"firing\", notify=\"off\", alertname=~\"$alertname\", name=~\"$name\"}"
    }
   ]
  }
 ]
}