# iperf3-server on nodes
# ====== [OLD] iperf3 over WireGuard (выключено по умолчанию) ======
node_iperf_enable: false
node_iperf_port: 5201
# Биндимся на WG-IP узла (роль node уже вычисляет/берёт wg_ip)
node_iperf_bind_ip: "{{ wg_ip }}"
# доп. аргументы iperf3 -s (например: "--one-off" чтобы завершаться после сессии)
node_iperf_extra_args: ""

# ====== [NEW] iperf3 public (direct) ======
node_iperf_public_enable: true
node_iperf_public_port: 5202
node_iperf_public_allow_ru_only: true
# (опц.) node_iperf_public_bind_ip: "0.0.0.0"

firewall_backend_override: "iptables"

# где лежит textfile collector
node_exporter_textfile_dir: /var/lib/node_exporter/textfile

# дефолты для uplink, если в vpn_nodes не указано
node_uplink_default_device: "ens3"
node_uplink_default_speed_bps: 1000000000   # 1 Gbit/s

# включить публикацию if_speed_bps через textfile
node_if_speed_textfile_enabled: true

# === Reality (XRAY/Marzban) textfile exporter ===
node_reality_enabled: true

# Где писать метрики
node_reality_textfile_dir: /var/lib/node_exporter/textfile

# XRAY/Marzban
node_reality_container_name: "^marzban-.*"    # можно шаблоном/regex (пример: "^marzban-node-.*")
node_reality_port: 443

# Имя узла в метриках (по умолчанию — inventory_hostname)
node_reality_node_name: "{{ inventory_hostname }}"

# systemd
node_reality_user: "{{ node_exporter_user | default('node_exporter') }}"
node_reality_group: "{{ node_exporter_group | default('node_exporter') }}"
node_reality_timeout: 60
node_reality_stdout: journal
node_reality_stderr: journal
node_reality_onboot: 30s
node_reality_interval: 60s
node_reality_accuracy: 10s

node_wg_user: "{{ node_exporter_user | default('node_exporter') }}"
node_wg_group: "{{ node_exporter_group | default('node_exporter') }}"
