---
- name: Create dirs
  ansible.builtin.file:
    path: "{{ monitoring_root }}/{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - prometheus
    - prometheus/rules
    - prometheus/targets
    - alertmanager
    - grafana
    - blackbox

- name: Render Prometheus config
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: "{{ monitoring_root }}/prometheus/prometheus.yml"
    mode: "0644"
  notify: Restart stack

- name: Render Alertmanager config
  ansible.builtin.template:
    src: alerts.yml.j2
    dest: "{{ monitoring_root }}/alertmanager/alertmanager.yml"
    mode: "0644"
  notify: Restart stack

- name: Render rules
  ansible.builtin.template:
    src: "rules/{{ item }}.yml.j2"
    dest: "{{ monitoring_root }}/prometheus/rules/{{ item }}.yml"
    mode: "0644"
  loop:
    - rec-network
    - rec-blackbox
    - rec-wireguard
    - rec-ru-probe
    - alerts-wireguard
  notify: Restart stack

- name: Render targets (file_sd)
  ansible.builtin.template:
    src: "targets/{{ item }}.json.j2"
    dest: "{{ monitoring_root }}/prometheus/targets/{{ item }}.json"
    mode: "0644"
  loop:
    - nodes
    - bb-icmp
    - bb-tcp443
  notify: Restart stack

- name: Render docker-compose
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ monitoring_root }}/docker-compose.yml"
    mode: "0644"

- name: Ensure docker compose stack is up
  community.docker.docker_compose_v2:
    project_src: "{{ monitoring_root }}"
    state: present
  notify: Restart stack
