- name: Render Prometheus config
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: "{{ monitoring_root }}/prometheus/prometheus.yml"
    mode: "0644"
  notify: Prometheus reload

# Собирам список шаблонов один раз (и упорядочиваем)
- name: Collect rules/targets templates
  ansible.builtin.set_fact:
    _rules_tpls: "{{ query('fileglob', role_path ~ '/templates/rules/*.yml.j2') | sort }}"
    _targets_tpls: "{{ query('fileglob', role_path ~ '/templates/targets/*.json.j2') | sort }}"

# Рендерим все rules/*.yml.j2 -> <monitoring_root>/prometheus/rules/*.yml
- name: Render Prometheus rules (auto)
  ansible.builtin.template:
    # src должен быть путём относительно каталога templates роли
    src: "{{ item | regex_replace('^' ~ (role_path ~ '/templates/'), '') }}"
    dest: "{{ monitoring_root }}/prometheus/rules/{{ (item | basename) | regex_replace('\\.yml\\.j2$', '.yml') }}"
    mode: "0644"
  loop: "{{ _rules_tpls }}"
  loop_control:
    label: "{{ item | basename }}"
  when: _rules_tpls | length > 0
  notify: Prometheus reload

- name: Build ru-probe targets (effective)
  ansible.builtin.set_fact:
    ru_probe_targets_eff: >-
      {{
        ru_probe_targets
          | default([{
              'address': (ru_probe_address | default(inventory_hostname ~ ':9100')),
              'labels': {
                'name': (ru_probe_name | default('RU-probe (' ~ inventory_hostname ~ ')')),
                'role': 'probe'
              }
            }])
      }}

# Рендерим все targets/*.json.j2 -> <monitoring_root>/prometheus/targets/*.json
- name: Render Prometheus targets (file_sd, auto)
  ansible.builtin.template:
    src: "{{ item | regex_replace('^' ~ (role_path ~ '/templates/'), '') }}"
    dest: "{{ monitoring_root }}/prometheus/targets/{{ (item | basename) | regex_replace('\\.json\\.j2$', '.json') }}"
    mode: "0644"
  loop: "{{ _targets_tpls }}"
  loop_control:
    label: "{{ item | basename }}"
  when: _targets_tpls | length > 0
  notify: Prometheus reload
