---
- name: RU probe | Present path
  ansible.builtin.include_tasks: present.yml
  when: ru_probe_state | lower == 'present'
  tags: [ru_probe]

- name: RU probe | Absent path
  ansible.builtin.include_tasks: absent.yml
  when: ru_probe_state | lower == 'absent'
  tags: [ru_probe]
