node_name: "nl-ams-1"
wg_ip: "10.77.0.2"
prom_role: "vpn"
uplink_device: "ens3"         # опц., по умолчанию ens3
uplink_speed_bps: 10000000000  # 10 Gbit/s
reality:
  e2e_enabled: true
  sni: "segment-ams-01.digitalstreamers.xyz"    
