---
- name: Derive wg_ip locally (hub-aware)
  ansible.builtin.set_fact:
    wg_ip: >-
      {{
        (
          hostvars[inventory_hostname].hub_wg_ip
          | default(hostvars[inventory_hostname].wg_ip
          | default(ansible_host))
          | string
        ).split('/')[0]
      }}
  when: wg_ip is not defined
  tags: [node_exporter]

- name: Install and run node_exporter (single @instance on WG IP)
  tags: [node_exporter]
  block:
    - name: Assert wg_ip is defined and valid
      ansible.builtin.assert:
        that:
          - wg_ip is defined
          - (wg_ip | ansible.utils.ipaddr) is not none
        fail_msg: "wg_ip не задан/некорректен для {{ inventory_hostname }}"

    - name: Ensure node_exporter system user
      ansible.builtin.user:
        name: node_exporter
        system: true
        shell: /usr/sbin/nologin
        create_home: false

    - name: Ensure textfile directory exists
      ansible.builtin.file:
        path: "{{ node_exporter_textfile_dir }}"
        state: directory
        owner: "{{ node_exporter_user | default('node_exporter') }}"
        group: "{{ node_exporter_group | default('node_exporter') }}"
        mode: "02775"   # setgid + групповая запись

    # 0) Есть ли бинарь вообще?
    - name: Check node_exporter binary presence
      ansible.builtin.stat:
        path: "{{ node_exporter_bin_dir }}/node_exporter"
      register: ne_stat
      changed_when: false

    # 1) Прочитать версию только если бинарь есть
    - name: Read installed node_exporter version (no shell)
      ansible.builtin.command: "{{ node_exporter_bin_dir }}/node_exporter --version"
      register: ne_ver
      changed_when: false
      failed_when: false
      when: ne_stat.stat.exists

    - name: Combine stdout+stderr for parsing
      ansible.builtin.set_fact:
        ne_ver_combined: "{{ (ne_ver.stdout | default('')) ~ '\n' ~ (ne_ver.stderr | default('')) }}"
      when: ne_stat.stat.exists

    - name: Parse existing version robustly
      ansible.builtin.set_fact:
        node_exporter_installed_version: "{{ (ne_ver_combined | regex_findall('version\\s+([0-9][^\\s]*)')) | first | default('') }}"
      when: ne_stat.stat.exists

    - name: Debug installed vs desired versions
      ansible.builtin.debug:
        msg: "installed={{ node_exporter_installed_version | default('') }}, desired={{ node_exporter_version }}"

    # Устанавливаем/обновляем только если версии нет или она отличается
    - name: Install/Update node_exporter from tarball
      when: node_exporter_installed_version | default('') != node_exporter_version
      block:
        - name: Download node_exporter archive
          ansible.builtin.get_url:
            url: >-
              {{ 'https://github.com/prometheus/node_exporter/releases/download/v'
                ~ node_exporter_version
                ~ '/node_exporter-'
                ~ node_exporter_version
                ~ '.'
                ~ node_exporter_arch
                ~ '.tar.gz' }}
            dest: "/tmp/node_exporter-{{ node_exporter_version }}.tar.gz"
            mode: "0644"
            timeout: 60
            headers:
              User-Agent: "curl/8.x ansible"
          register: dl_ne
          until: dl_ne is succeeded
          retries: 4
          delay: 10

        - name: Unpack node_exporter
          ansible.builtin.unarchive:
            src: "/tmp/node_exporter-{{ node_exporter_version }}.tar.gz"
            dest: "/tmp"
            remote_src: true
            creates: "/tmp/node_exporter-{{ node_exporter_version }}.{{ node_exporter_arch }}/node_exporter"

        - name: Install node_exporter binary
          ansible.builtin.copy:
            src: "/tmp/node_exporter-{{ node_exporter_version }}.{{ node_exporter_arch }}/node_exporter"
            dest: "{{ node_exporter_bin_dir }}/node_exporter"
            owner: root
            group: root
            mode: "0755"
            remote_src: true
          notify: Restart node_exporter instance

    - name: Deploy templated systemd unit (@instance)
      ansible.builtin.template:
        src: node_exporter@.service.j2
        dest: /etc/systemd/system/node_exporter@.service
        mode: "0644"
      notify: Restart node_exporter instance

    - name: Reload systemd
      ansible.builtin.systemd:
        daemon_reload: true

    - name: Enable and start node_exporter@{{ node_exporter_listen }}
      ansible.builtin.systemd:
        name: "node_exporter@{{ node_exporter_listen }}"
        enabled: true
        state: started

    - name: Configure ufw for node_exporter
      ansible.builtin.include_role:
        name: ufw_firewall
      when: firewall_ufw_manage | bool
      vars:
        ufw_firewall_rules:
          - rule: allow
            proto: tcp
            port: "{{ node_exporter_port }}"
            from_ip: "{{ wg_subnet_cidr }}"
            comment: "node_exporter @{{ node_exporter_listen }}"
