---
- name: Speedtest | Install systemd service
  ansible.builtin.template:
    src: speedtest-textfile-ookla.service.j2
    dest: /etc/systemd/system/speedtest-textfile-ookla.service
    owner: root
    group: root
    mode: "0644"
  notify: Reload systemd

- name: Speedtest | Install systemd timer
  ansible.builtin.template:
    src: speedtest-textfile-ookla.timer.j2
    dest: /etc/systemd/system/speedtest-textfile-ookla.timer
    owner: root
    group: root
    mode: "0644"
  notify: Reload systemd
