---
# Speedtest (Ookla) → node_exporter textfile (минимальный набор)
# Ожидаемые vars (см. defaults):
# - node_speedtest_enabled: true|false
# - node_speedtest_install: true|false
# - node_speedtest_textdir: /var/lib/node_exporter/textfile
# - node_speedtest_bin: /usr/bin/speedtest
# - node_speedtest_timer_enabled: true|false
# - node_speedtest_oncalendar: "*-*-* 06,18:00:00"
# - node_speedtest_randomized_delay_sec: 900
#
# Для Prometheus API basic-auth, если нужно:
# - node_speedtest_prom_url
# - node_speedtest_prom_user
# - node_speedtest_prom_pass
#
# Теги:
#   speedtest_ookla — весь пайплайн
#   speedtest_install — только установка бинаря
#   speedtest_timer — операции с таймером/юнитами

- name: Speedtest_ookla | prerequisites
  ansible.builtin.import_tasks: 01_prereqs.yml
  tags: [speedtest_ookla]

- name: Speedtest_ookla | detect current state
  ansible.builtin.import_tasks: 02_detect.yml
  tags: [speedtest_ookla, speedtest_install]

- name: Speedtest_ookla | install via repo when possible
  ansible.builtin.import_tasks: 03_install_repo.yml
  when:
    - node_speedtest_enabled | bool
    - node_speedtest_install | bool
    - not speedtest_present | default(false)
  tags: [speedtest_ookla, speedtest_install]

- name: Speedtest_ookla | fallback direct install
  ansible.builtin.import_tasks: 04_install_direct.yml
  when:
    - node_speedtest_enabled | bool
    - node_speedtest_install | bool
    - not speedtest_present | default(false)
    - not (_speedtest_repo_ok | default(false))
  tags: [speedtest_ookla, speedtest_install]

- name: Speedtest_ookla | deploy textfile script
  ansible.builtin.import_tasks: 10_script.yml
  when: node_speedtest_enabled | bool
  tags: [speedtest_ookla]

- name: Speedtest_ookla | systemd units
  ansible.builtin.import_tasks: 20_systemd.yml
  when: node_speedtest_enabled | bool
  tags: [speedtest_ookla, speedtest_timer]

- name: Speedtest_ookla | systemd timer control
  ansible.builtin.import_tasks: 21_timer.yml
  when: node_speedtest_enabled | bool
  tags: [speedtest_ookla, speedtest_timer]
