---
# Reality E2E — orchestrator
- name: Reality E2E | Import setup
  ansible.builtin.import_tasks: 00_setup.yml
  tags: [reality_e2e, reality_e2e_setup]

- name: Reality E2E | Ensure util-linux (flock)
  ansible.builtin.import_tasks: 05_packages.yml
  tags: [reality_e2e, reality_e2e_setup]

- name: Reality E2E | Render profiles
  ansible.builtin.import_tasks: 10_render_profiles.yml
  tags: [reality_e2e, reality_e2e_profiles]

- name: Reality E2E | Deploy probe script
  ansible.builtin.import_tasks: 20_deploy_script.yml
  tags: [reality_e2e, reality_e2e_script]

- name: Reality E2E | Deploy systemd units
  ansible.builtin.import_tasks: 21_deploy_units.yml
  tags: [reality_e2e, reality_e2e_systemd]

- name: Reality E2E | Apply systemd daemon-reload now
  ansible.builtin.meta: flush_handlers
  tags: [reality_e2e, reality_e2e_systemd]

- name: Reality E2E | Enable & start timers
  ansible.builtin.import_tasks: 30_enable_timers.yml
  tags: [reality_e2e, reality_e2e_systemd]

- name: Reality E2E | Prune stale profiles/timers/tmp
  ansible.builtin.import_tasks: 90_prune.yml
  tags: [reality_e2e, reality_e2e_prune]

- name: Reality E2E | Post actions
  ansible.builtin.import_tasks: 99_post.yml
  tags: [reality_e2e]
