---
# Берём из host_vars текущего хоста; если не задано — подставляем дефолты роли
- name: IfSpeed | Derive uplink_device from hostvars or defaults
  ansible.builtin.set_fact:
    node_uplink_device_effective: >-
      {{
        hostvars[inventory_hostname].uplink_device
        | default(node_uplink_default_device)
      }}

- name: IfSpeed | Derive uplink_speed_bps from hostvars or defaults
  ansible.builtin.set_fact:
    node_uplink_speed_bps_effective: >-
      {{
        (hostvars[inventory_hostname].uplink_speed_bps
         | default(node_uplink_default_speed_bps)) | int
      }}

- name: IfSpeed | Publish if_speed_bps via textfile
  when: node_if_speed_textfile_enabled | bool
  ansible.builtin.template:
    src: if_speed.prom.j2
    dest: "{{ node_exporter_textfile_dir }}/if_speed.prom"
    owner: root
    group: root
    mode: "0644"
