---
# --- Firewall backend detection (для всех последующих шагов node) ---
- name: Node | Include firewall detection
  ansible.builtin.include_tasks: firewall_detect.yml
  tags: [node, firewall, firewall_detect, node_iperf, iperf3_public, iperf3, iperf3_cleanup]

- name: Node | Include iperf3 server tasks
  ansible.builtin.include_tasks: iperf.yml
  tags: [node, node_iperf, iperf3]

- name: Include if_speed tasks
  ansible.builtin.import_tasks: if_speed.yml
  tags: [node_if_speed]

- name: Include reality service health exporter
  ansible.builtin.import_tasks: reality.yml
  tags: [node_reality, reality]

- name: Include WG textfile metrics tasks
  ansible.builtin.import_tasks: wg_metrics.yml
  tags: [node_wg_metrics]

- name: Node | cleanup iperf3 server tasks
  ansible.builtin.import_tasks: iperf_cleanup.yml
  tags: [node, node_iperf, iperf3_cleanup]

- name: Node | Include public iperf3 server tasks
  ansible.builtin.include_tasks: iperf_public.yml
  when: node_iperf_public_enable | bool
  tags: [node, node_iperf, iperf3_public]
