---
- name: Node | Include iperf3 server tasks
  ansible.builtin.include_tasks: iperf.yml
  tags: [node, node_iperf, iperf3]

- name: Include if_speed tasks
  ansible.builtin.import_tasks: if_speed.yml
  tags: [node_if_speed]

- name: Include reality service health exporter
  ansible.builtin.import_tasks: reality.yml
  tags: [node_reality, reality]

- name: Include WG textfile metrics tasks
  ansible.builtin.import_tasks: wg_metrics.yml
  tags: [node_wg_metrics]
