---
- name: WireGuard facts | Lookup vpn_nodes entry for this host
  ansible.builtin.set_fact:
    wireguard_node_entry: >-
      {{
        (vpn_nodes | default([]) | selectattr('name', 'equalto', inventory_hostname) | list | first)
      }}
  when:
    - vpn_nodes is defined
    - wireguard_node_entry is not defined
  tags: [wireguard, wg_facts]

- name: WireGuard facts | Derive wg_ip from entry
  ansible.builtin.set_fact:
    wg_ip: "{{ wireguard_node_entry.wg_ip }}"
  when:
    - wg_ip is not defined
    - wireguard_node_entry is defined
    - wireguard_node_entry.wg_ip is defined
  tags: [wireguard, wg_facts]

- name: WireGuard facts | Normalize wg_ip to string
  ansible.builtin.set_fact:
    wg_ip: "{{ wg_ip | string }}"
  when: wg_ip is defined
  tags: [wireguard, wg_facts]

- name: WireGuard facts | Derive /24 subnet cidr from wg_ip
  ansible.builtin.set_fact:
    wg_subnet_cidr: "{{ (wg_ip | regex_replace('\\.\\d+$', '.0')) }}/24"
  when:
    - wg_ip is defined
    - wg_ip | length > 0
  tags: [wireguard, wg_facts]

- name: WireGuard facts | Remember hub inventory host (if any)
  ansible.builtin.set_fact:
    wireguard_hub_inventory_host: "{{ groups['hub'][0] }}"
  when:
    - wireguard_hub_inventory_host is not defined
    - groups['hub'] is defined
    - groups['hub'] | length > 0
  tags: [wireguard, wg_facts]

- name: WireGuard facts | Derive effective hub wg_ip
  ansible.builtin.set_fact:
    hub_wg_ip_effective: >-
      {{
        hub_wg_ip
        | default(
            hostvars.get(wireguard_hub_inventory_host | default(''), {})
                     .get('hub_wg_ip',
                          hostvars.get(wireguard_hub_inventory_host | default(''), {})
                                  .get('wg_ip', '')
                     )
          )
      }}
  when: hub_wg_ip_effective is not defined
  tags: [wireguard, wg_facts]

- name: WireGuard facts | Provide /32 hub cidr helper
  ansible.builtin.set_fact:
    hub_wg_ip_cidr32: "{{ hub_wg_ip_effective }}/32"
  when:
    - hub_wg_ip_effective is defined
    - hub_wg_ip_effective | length > 0
  tags: [wireguard, wg_facts]

- name: WireGuard facts | Mark consolidation complete
  ansible.builtin.set_fact:
    wireguard_facts_loaded: true
  tags: [wireguard, wg_facts]
