---
- name: Hub (monitoring server)
  hosts: hub
  roles:
    - { role: docker, when: docker_install | bool, tags: [docker] }   # установка Docker/Compose
    - { role: nginx, tags: [nginx] }    # reverse-proxy, certs, htpasswd
    - { role: hub, tags: [hub] }
    - { role: ru_probe, when: ru_probe_enabled | bool, tags: [ru_probe] }

- name: VPN nodes
  hosts: vpn
  roles:
    - node
