- name: Detect if current host is the hub
  ansible.builtin.set_fact:
    is_hub: "{{ inventory_hostname in (groups['hub'] | default([])) }}"

# На хабе — ничего не трогаем в WG (но оставляем возможность расширить поведение позже)
- name: Skipping wireguard_node on hub
  ansible.builtin.debug:
    msg: "wireguard_node: skip mutating WG config on hub {{ inventory_hostname }}"
  when: is_hub | bool

# На НЕ-хабах выполняем обычную «узловую» конфигурацию WG
- name: Configure WG node (non-hub)
  ansible.builtin.import_tasks: node.yml
  when: not is_hub | bool
